export const Tabuleiro = [
    { peca: 'torre', cor: '#fff' },
    { peca: 'cavalo', cor: '#fff' },
    { peca: 'bispo', cor: '#fff' },
    { peca: 'rei', cor: '#fff' },
    { peca: 'rainha', cor: '#fff' },
    { peca: 'bispo', cor: '#fff' },
    { peca: 'cavalo', cor: '#fff' },
    { peca: 'torre', cor: '#fff' },
    { peca: 'peao', cor: '#fff' },
    { peca: 'peao', cor: '#fff' },
    { peca: 'peao', cor: '#fff' },
    { peca: 'peao', cor: '#fff' },
    { peca: 'peao', cor: '#fff' },
    { peca: 'peao', cor: '#fff' },
    { peca: 'peao', cor: '#fff' },
    { peca: 'peao', cor: '#fff' },
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    { peca: 'peao', cor: '#000' },
    { peca: 'peao', cor: '#000' },
    { peca: 'peao', cor: '#000' },
    { peca: 'peao', cor: '#000' },
    { peca: 'peao', cor: '#000' },
    { peca: 'peao', cor: '#000' },
    { peca: 'peao', cor: '#000' },
    { peca: 'peao', cor: '#000' },
    { peca: 'torre', cor: '#000' },
    { peca: 'cavalo', cor: '#000' },
    { peca: 'bispo', cor: '#000' },
    { peca: 'rei', cor: '#000' },
    { peca: 'rainha', cor: '#000' },
    { peca: 'bispo', cor: '#000' },
    { peca: 'cavalo', cor: '#000' },
    { peca: 'torre', cor: '#000' },
]
